name: cheat
version: 'v3.8.0.build.1'
summary: cheat allows to create and view interactive cheatsheets on the command-line.
description: |
  cheat allows you to create and view interactive cheatsheets on the command-line. 
  It was designed to help remind *nix system administrators of options for commands 
  that they use frequently, but not frequently enough to remember.
  Source comes from https://github.com/cheat
  Bugreports for upstream go to: https://github.com/cheat/cheat/issues
  Bugreports for snap go to: https://github.com/cheat/snap/issues

grade: stable
confinement: strict
base: core18

layout:
  /usr/share/cheat:
    symlink: $SNAP/usr/share/cheat
  /etc/nanorc:
    bind-file: $SNAP/etc/nanorc
  /usr/share/git-core/templates:
    symlink: $SNAP/usr/share/git-core/templates

apps:
  cheat:
    command: cheat
    plugs: [home]

  vi:
    command: vim

  vim:
    command: vim

  nano:
    command: nano

  git:
    command: git

parts:
  cheat:
    plugin: go
    go-importpath: github.com/cheat/cheat
    source: https://github.com/cheat/cheat
    source-type: git
    build-packages:
      - pandoc
    stage-packages:
      - libcurl4
      - git
    override-build: |
      export GOPATH=$(realpath ../go)
      mkdir -p ${SNAPCRAFT_PART_INSTALL}/bin/
      cd ${SNAPCRAFT_PART_SRC}
      sed -i 's/https:\/\/github.com/git:\/\/github.com/g' internal/installer/clone.go
      make build
      cp dist/cheat ${SNAPCRAFT_PART_INSTALL}/bin/

      mkdir -p $SNAPCRAFT_PRIME/etc/
      touch $SNAPCRAFT_PRIME/etc/nanorc

      mkdir -p $SNAPCRAFT_PRIME/usr/share/git-core/templates

  vim:
    source: https://github.com/vim/vim.git
    source-depth: 1
    plugin: autotools

  nano:
    source: https://www.nano-editor.org/dist/latest/nano-4.9.tar.gz
    source-type: tar
    plugin: autotools
    build-packages:
      - gcc
      - libncurses5-dev
