name: cheat
version: 'v3.2.1.build.0'
summary: cheat allows to create and view interactive cheatsheets on the command-line.
description: |
  cheat allows you to create and view interactive cheatsheets on the command-line. 
  It was designed to help remind *nix system administrators of options for commands 
  that they use frequently, but not frequently enough to remember.
  Source comes from https://github.com/cheat
  Bugreports go to: https://github.com/cheat/issues

grade: stable
confinement: strict
base: core18

layout:
  /bin/vi:
    symlink: $SNAP/bin/vim
  /etc/cheat/conf.yml:
    bind-file: $SNAP_DATA/etc/cheat/conf.yml

apps:
  cheat:
    command: cheat

  vi:
    command: vim

  vim:
    command: vim

  nano:
    command: nano

parts:
  cheat:
    plugin: dump
    source: .
    override-pull: |
      cd "$SNAPCRAFT_PART_SOURCE"
      curl -sSLO  https://github.com/cheat/cheat/releases/download/3.2.1/cheat-linux-amd64
      mv cheat-linux-amd64 cheat
      chmod +x cheat
      curl -sSLO  https://github.com/cheat/cheatsheets/archive/master.zip 

  vim:
    source: https://github.com/vim/vim.git
    plugin: make
    override-build: |
      cd src
      ./configure --prefix=$SNAPCRAFT_PART_INSTALL
      make
      make install

  nano:
    source: https://www.nano-editor.org/dist/latest/nano-4.6.tar.gz
    source-type: tar
    plugin: make
    override-build: |
      ./configure --prefix=$SNAPCRAFT_PART_INSTALL
      make
      make install
    override-prime: |
      snapcraftctl prime
    build-packages:
      - gcc
      - libncurses5-dev
