name: cheat
version: 'v3.2.1.build.1'
summary: cheat allows to create and view interactive cheatsheets on the command-line.
description: |
  cheat allows you to create and view interactive cheatsheets on the command-line. 
  It was designed to help remind *nix system administrators of options for commands 
  that they use frequently, but not frequently enough to remember.
  Source comes from https://github.com/cheat
  Bugreports go to: https://github.com/cheat/issues

grade: stable
confinement: strict
base: core18

layout:
  /bin/vi:
    symlink: $SNAP/bin/vim

apps:
  cheat:
    environment:
      CHEAT_CONFIG_PATH: "$SNAP_DATA/usr/share/cheat/conf.yml"
    command: cheat
    plugs: [home]

  vi:
    command: vim

  vim:
    command: vim

  nano:
    command: nano

architectures:
  - build-on: amd64

parts:
  cheat:
    plugin: dump
    source: .
    override-pull: |
      cd "$SNAPCRAFT_PART_SRC"
      curl -sSLO  https://github.com/cheat/cheat/releases/download/3.2.1/cheat-linux-amd64
      mv cheat-linux-amd64 cheat
      chmod +x cheat

      mkdir -p $SNAPCRAFT_PRIME/usr/share/cheat/cheatsheets
      if [ -d $SNAPCRAFT_PRIME/usr/share/cheat/cheatsheets/community ]; then
        cd $SNAPCRAFT_PRIME/usr/share/cheat/cheatsheets/community
        git fetch
        git pull
      else
        git clone https://github.com/cheat/cheatsheets $SNAPCRAFT_PRIME/usr/share/cheat/cheatsheets/community
      fi
    build-packages:
        - curl

  vim:
    source: https://github.com/vim/vim.git
    source-depth: 1
    plugin: make
    override-build: |
      cd src
      ./configure --prefix=$SNAPCRAFT_PART_INSTALL
      make
      make install

  nano:
    source: https://www.nano-editor.org/dist/latest/nano-4.6.tar.gz
    source-type: tar
    plugin: make
    override-build: |
      ./configure --prefix=$SNAPCRAFT_PART_INSTALL
      make
      make install
    override-prime: |
      snapcraftctl prime
    build-packages:
      - gcc
      - libncurses5-dev
