name: cheat
version: 'v4.2.0.build.3'
summary: cheat allows to create and view interactive cheatsheets on the command-line.
description: |
  cheat allows you to create and view interactive cheatsheets on the command-line. 
  It was designed to help remind *nix system administrators of options for commands 
  that they use frequently, but not frequently enough to remember.
  Source comes from https://github.com/cheat
  Bugreports for upstream go to: https://github.com/cheat/cheat/issues
  Bugreports for snap go to: https://github.com/cheat/snap/issues

grade: stable
confinement: strict
base: core20

layout:
  /usr/share/cheat:
    symlink: $SNAP/usr/share/cheat
  /etc/nanorc:
    bind-file: $SNAP/etc/nanorc
  /usr/share/git-core/templates:
    symlink: $SNAP/usr/share/git-core/templates

apps:
  cheat:
    command: usr/local/bin/cheat
    plugs:
      - home
      - network
      - avahi-observe
    environment:
      HOME: "$SNAP_USER_COMMON"

  vim:
    command: usr/local/bin/vim

  nano:
    command: usr/local/bin/nano

  update:
    command: usr/local/bin/update
    plugs:
      - network
      - avahi-observe

parts:
  cheat:
    plugin: go
    source: https://github.com/cheat/cheat
    source-type: git
    build-packages:
      - pandoc
      - make
    stage-packages:
      - git
    override-build: |
      export GOPATH=$(realpath ../go)
      mkdir -p ${SNAPCRAFT_PART_INSTALL}/usr/local/bin/
      cd ${SNAPCRAFT_PART_SRC}

      # customize cheat help:
      ## drop lines containing config as this is different in snap version
      sed -i '/config/d' cmd/cheat/docopt.txt
      ## adding some documentation for updating community cheatsheets
      sed -i '3aUpdate community cheatsheets via:\n  cheat.update\n\n' cmd/cheat/docopt.txt

      # atm snap version does not support https
      sed -i 's/https:\/\/github.com/git:\/\/github.com/g' internal/installer/clone.go

      # build cheat
      make build
      cp dist/cheat ${SNAPCRAFT_PART_INSTALL}/usr/local/bin/

      # nessesary for working git
      mkdir -p $SNAPCRAFT_PRIME/usr/share/git-core/templates

  update:
    plugin: dump
    source: scripts/git
    source-type: local
    organize:
      "*": usr/local/bin/

  vim:
    source: https://github.com/vim/vim.git
    source-depth: 1
    plugin: autotools
    override-prime: |
      snapcraftctl prime
      cd $SNAPCRAFT_PRIME/usr/bin
      [ -f vim ] && rm vim || :
      ln -s ../local/bin/vim vim

  nano:
    source: https://www.nano-editor.org/dist/latest/nano-5.6.1.tar.gz
    source-type: tar
    plugin: autotools
    build-packages:
      - gcc
      - libncurses5-dev
    override-build: |
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PRIME/etc/
      touch $SNAPCRAFT_PRIME/etc/nanorc
    override-prime: |
      snapcraftctl prime
      cd $SNAPCRAFT_PRIME/usr/bin
      [ -f nano ] && rm nano || :
      ln -s ../local/bin/nano nano

