name: cheat
version: 4.3.3.build.3
summary: cheat allows to create and view interactive cheatsheets on the command-line.
description: |
  cheat allows you to create and view interactive cheatsheets on the command-line. 
  It was designed to help remind *nix system administrators of options for commands 
  that they use frequently, but not frequently enough to remember.
  Source comes from https://github.com/cheat
  Bugreports for upstream go to: https://github.com/cheat/cheat/issues
  Bugreports for snap go to: https://github.com/cheat/snap/issues

grade: stable
confinement: strict
base: core20

layout:
  /etc/nanorc:
    bind-file: $SNAP/etc/nanorc

apps:
  cheat:
    command: usr/local/bin/cheat
    plugs:
      - home
      - network
      - avahi-observe
    environment:
      HOME: "$SNAP_USER_COMMON"

  vim:
    command: usr/local/bin/vim

  nano:
    command: usr/local/bin/nano

parts:
  cheat:
    plugin: dump
    source:
      - on amd64: https://github.com/cheat/cheat/releases/download/4.3.3/cheat-linux-amd64.gz
      - on arm64: https://github.com/cheat/cheat/releases/download/4.3.3/cheat-linux-arm64.gz
      - on armhf: https://github.com/cheat/cheat/releases/download/4.3.3/cheat-linux-arm7.gz
    source-type: 7z
    organize:
      cheat-linux-amd64: /usr/local/bin/cheat
      cheat-linux-arm64: /usr/local/bin/cheat
      cheat-linux-arm7: /usr/local/bin/cheat
    override-prime: |
      snapcraftctl prime
      chmod +x $SNAPCRAFT_PRIME/usr/local/bin/cheat

  vim:
    source: https://github.com/vim/vim.git
    source-depth: 1
    plugin: autotools
    override-prime: |
      snapcraftctl prime
      mkdir -p $SNAPCRAFT_PRIME/usr/bin
      cd $SNAPCRAFT_PRIME/usr/bin
      [ -f vim ] && rm vim || :
      ln -s ../local/bin/vim vim

  nano:
    source: https://www.nano-editor.org/dist/latest/nano-6.4.tar.gz
    source-type: tar
    plugin: autotools
    build-packages:
      - gcc
      - libncurses5-dev
    override-build: |
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PRIME/etc/
      touch $SNAPCRAFT_PRIME/etc/nanorc
    override-prime: |
      snapcraftctl prime
      mkdir -p $SNAPCRAFT_PRIME/usr/bin
      cd $SNAPCRAFT_PRIME/usr/bin
      [ -f nano ] && rm nano || :
      ln -s ../local/bin/nano nano

