name: cheat
version: 'v2.4.2.build.3'
summary: cheat allows to create and view interactive cheatsheets on the command-line.
description: |
  cheat allows you to create and view interactive cheatsheets on the command-line. 
  It was designed to help remind *nix system administrators of options for commands 
  that they use frequently, but not frequently enough to remember.
  Source comes from https://github.com/chrisallenlane

grade: stable
confinement: strict

apps:
  cheat:
    environment: 
      CHEAT_PATH: "$SNAP/lib/python2.7/site-packages/usr/share/cheat/"
      PYTHONIOENCODING: 'utf-8'
    command: cheat
    plugs: [home]

  vim:
    command: vim

  nano:
    command: nano

hooks:
  configure:
    plugs: [home]

parts:
  cheat:
    source: https://github.com/chrisallenlane/cheat.git
    source-branch: refactor
    plugin: python
    python-version: python2
    python-packages:
      - termcolor
      - docopt
      - pygments

  vim:
    source: https://github.com/vim/vim.git
    plugin: autotools
    install-via: destdir
    #make-install-var: DESTDIR=$SNAPCRAFT_PART_INSTALL

  nano:
    source: https://www.nano-editor.org/dist/v3/nano-3.2.tar.gz
    source-type: tar
    plugin: autotools
    install-via: destdir
    #override-build: |
    #  ./configure
    #  make
    #  make install DESTDIR=$SNAPCRAFT_PART_INSTALL
