name: cheat
version: 'v2.5.1.build.7'
summary: cheat allows to create and view interactive cheatsheets on the command-line.
description: |
  cheat allows you to create and view interactive cheatsheets on the command-line. 
  It was designed to help remind *nix system administrators of options for commands 
  that they use frequently, but not frequently enough to remember.
  Source comes from https://github.com/cheat
  Bugreports go to: https://github.com/cheat/issues

grade: stable
confinement: strict
base: core18

layout:
  /bin/vi:
    symlink: $SNAP/bin/vim

apps:
  cheat:
    environment:
      CHEAT_PATH: "$SNAP/lib/python3.6/site-packages/root/.local/share/cheat/"
      PYTHONIOENCODING: 'utf-8'
      CHEAT_COLORS: "true"
      CHEAT_HIGHLIGHT: "red"
    command: cheat
    plugs: [home]

  vi:
    command: vim

  vim:
    command: vim

  nano:
    command: nano

parts:
  cheat:
    source: https://github.com/cheat/cheat.git
    plugin: python
    python-packages:
      - appdirs
      - termcolor
      - docopt
      - pygments

  vim:
    source: https://github.com/vim/vim.git
    plugin: make
    override-build: |
      cd src
      ./configure --prefix=$SNAPCRAFT_PART_INSTALL
      make
      make install

  nano:
    source: https://www.nano-editor.org/dist/latest/nano-4.5.tar.gz
    source-type: tar
    plugin: make
    override-build: |
      ./configure --prefix=$SNAPCRAFT_PART_INSTALL
      make
      make install
    override-prime: |
      snapcraftctl prime
    build-packages:
      - libncurses5-dev
