name: cheat # you probably want to 'snapcraft register <name>'
version: 'v2.4.2.build.1'
summary: cheat allows to create and view interactive cheatsheets on the command-line.
description: |
  cheat allows you to create and view interactive cheatsheets on the command-line. 
  It was designed to help remind *nix system administrators of options for commands 
  that they use frequently, but not frequently enough to remember.
  Source comes from https://github.com/cheat

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  cheat:
    environment: 
      CHEAT_EDITOR: nano
      CHEAT_PATH: "$SNAP/lib/python2.7/site-packages/usr/share/cheat/"
      PYTHONIOENCODING: 'utf-8'
    command: cheat
    plugs: [home]
    
parts:
  cheat:
    source: https://github.com/cheat/cheat.git
    source-branch: master
    plugin: python
    python-version: python2
    python-packages:
      - termcolor
      - docopt
      - pygments
    stage-packages: 
      - nano
